# Generated by Django 4.2.5 on 2023-10-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
